#!/bin/bash
# Please run the following commands as root!

#====================================================
# Install Hbase 
#====================================================
echo "Installing ......"

# download hbase
#wget http://apache.dataguru.cn/hadoop/core/hadoop-1.2.1/hadoop-1.2.1.tar.gz
file=./tar/hbase-0.94.12.tar.gz
tar xzf $file 
mv hbase-0.94.12 hbase

# configure JAVA_HOME and HBASE_CLASSPATH for hbase
dst=./hbase/conf
file=$dst/hbase-env.sh
cat >>$file <<EOF
export JAVA_HOME=${JAVA_HOME}
export HBASE_CLASSPATH=/home/hduser/hadoop/conf
EOF



# configure JAVA_HOME for hbase

# configure confs for hbase
file=./conf/hbase/hbase-site.xml 
cp $file $dst/

# move hbase to dest folder
#============================================
INSTALL_FOLDER=/home/hduser
#============================================

dst=$INSTALL_FOLDER
mv ./hbase $dst

# change ownerships of hbase
chown -R hduser:hadoop $dst

echo "Finished!"
