#!/bin/bash
# Please run the following commands as root!
#============================================
INSTALL_FOLDER=/home/hduser
#============================================

# update regionservers for hbase
dst=$INSTALL_FOLDER/hbase/conf
file=./conf/hbase/regionservers
cp $file $dst/regionservers

# change ownership of hbase
chown -R hduser:hadoop $dst
echo "Finished."
