#!/bin/bash
# Please run the following commands as root!

#====================================================
# Install Hadoop 
#====================================================
echo "Installing ......"

# download hadoop
#wget http://apache.dataguru.cn/hadoop/core/hadoop-1.2.1/hadoop-1.2.1.tar.gz
file=./tar/hadoop-1.2.1.tar.gz
tar xzf $file 
mv hadoop-1.2.1 hadoop

# configure JAVA_HOME for hadoop
dst=./hadoop/conf
file=$dst/hadoop-env.sh
cat >>$file <<EOF
export JAVA_HOME=${JAVA_HOME}
EOF

# configure confs for hbase
file=./conf/hadoop/core-site.xml 
cp $file $dst/
file=./conf/hadoop/mapred-site.xml
cp $file $dst/
file=./conf/hadoop/hdfs-site.xml
cp $file $dst/

# move hadoop to dest folder
#============================================
#INSTALL_FOLDER=/home/hduser/test
INSTALL_FOLDER=/home/hduser
#============================================

dst=$INSTALL_FOLDER
mv ./hadoop $dst

# change ownerships of hadoop
chown -R hduser:hadoop $dst

echo "Finished!"
