#!/bin/bash
# Please run the following commands as root!
#============================================
#INSTALL_FOLDER=/home/hduser/test
INSTALL_FOLDER=/home/hduser
#============================================

# update conf/masters conf/slaves for master node
dst=$INSTALL_FOLDER/hadoop/conf
file=./conf/hadoop/masters
cp $file $dst/masters

file=./conf/hadoop/slaves
cp $file $dst/slaves

# change ownership of hadoop
chown -R hduser:hadoop $dst
echo "Finished."
