#!/bin/bash
file=/etc/sysctl.conf
cat >> $file <<EOF
# disable ipv6 by kezunlin
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF

echo "========================================"
tail -4 $file
echo "========================================"
# You have to reboot your machine in order to make the changes take effect.
# You can check whether IPv6 is enabled on your machine with the following command:
cat /proc/sys/net/ipv6/conf/all/disable_ipv6
# 0 enabled, 1 disable

